In [3]:
import pandas as pd

In [4]:
#Reading the csv files

appearances = pd.read_csv('archive/appearances.csv')
club_games = pd.read_csv('archive/club_games.csv')
competitions = pd.read_csv('archive/competitions.csv')
game_events = pd.read_csv('archive/game_events.csv')
game_lineups = pd.read_csv('archive/game_lineups.csv')
games = pd.read_csv('archive/games.csv')
player_valuations = pd.read_csv('archive/player_valuations.csv')
players = pd.read_csv('archive/players.csv')
clubs = pd.read_csv('archive/clubs.csv')

In [5]:
#Filtering for active players in players

condition_active_players = (players['last_season'] == 2023)
active_players = players[condition_active_players]
active_players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
188,3333,James,Milner,James Milner,2023,1237,james-milner,England,Leeds,England,...,right,175.0,2024-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/james-milner/p...,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0
348,4391,Boy,Waterman,Boy Waterman,2023,383,boy-waterman,Netherlands,Lelystad,Netherlands,...,right,188.0,2024-06-30 00:00:00,Sp international,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/boy-waterman/p...,NL1,Eindhovense Voetbalvereniging Philips Sport Ve...,75000.0,3000000.0
417,5336,Anastasios,Tsokanis,Anastasios Tsokanis,2023,60949,anastasios-tsokanis,Greece,Chalkida,Greece,...,left,176.0,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/anastasios-tso...,GR1,Neos Podosferikos Syllogos Volou,450000.0,450000.0
644,7161,Jonas,Hofmann,Jonas Hofmann,2023,15,jonas-hofmann,Germany,Heidelberg,Germany,...,right,176.0,2027-06-30 00:00:00,Dr. Marco Gutfleisch,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/jonas-hofmann/...,L1,Bayer 04 Leverkusen Fußball,13000000.0,16000000.0
723,7825,Pepe,Reina,Pepe Reina,2023,1050,pepe-reina,Spain,Madrid,Spain,...,right,188.0,2024-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/pepe-reina/pro...,ES1,Villarreal Club de Fútbol S.A.D.,700000.0,22000000.0

In [6]:
game_lineups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2191911 entries, 0 to 2191910
Data columns (total 10 columns):
 #   Column           Dtype
---  ------           -----
 0   game_lineups_id  object
 1   date             object
 2   game_id          int64
 3   player_id        int64
 4   club_id          int64
 5   player_name      object
 6   type             object
 7   position         object
 8   number           object
 9   team_captain     int64
dtypes: int64(4), object(6)
memory usage: 167.2+ MB

In [7]:
game_lineups.head()

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

In [8]:
#Filtering for active players in game_lineups

active_players_id = active_players["player_id"]
active_game_lineups = game_lineups[game_lineups["player_id"].isin(active_players_id)]
active_game_lineups.head()

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
6,d196e3ec2f03110a523b6eaa65027f07,2013-07-27,2317258,30290,610,Kenneth Vermeer,starting_lineup,Goalkeeper,1,0
7,e9e1212e3ba0dabdf39f45ce631799f7,2013-07-27,2317258,34784,610,Lasse Schöne,starting_lineup,Defensive Midfield,20,0
10,1412e8a9285378507537c6346c77c6ff,2013-07-27,2317258,42710,610,Toby Alderweireld,starting_lineup,Centre-Back,3,0
15,ac1c4c90cf314ad3f4f247be447acba9,2013-07-27,2317258,69633,610,Christian Eriksen,starting_lineup,Central Midfield,8,0

In [9]:
#Filtering for active players in player valuations

active_player_valuations = player_valuations[player_valuations["player_id"].isin(active_players_id)]
active_player_valuations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 109233 entries, 188 to 467137
Data columns (total 5 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   player_id                            109233 non-null  int64
 1   date                                 109233 non-null  object
 2   market_value_in_eur                  109233 non-null  int64
 3   current_club_id                      109233 non-null  int64
 4   player_club_domestic_competition_id  109233 non-null  object
dtypes: int64(3), object(2)
memory usage: 5.0+ MB

In [10]:
#Filtering for active players in games using active_game_lineups

active_games_id = active_game_lineups["game_id"]
active_games = games[games["game_id"].isin(active_games_id)]
active_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53888 entries, 0 to 68148
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 53888 non-null  int64
 1   competition_id          53888 non-null  object
 2   season                  53888 non-null  int64
 3   round                   53888 non-null  object
 4   date                    53888 non-null  object
 5   home_club_id            53888 non-null  int64
 6   away_club_id            53888 non-null  int64
 7   home_club_goals         53888 non-null  int64
 8   away_club_goals         53888 non-null  int64
 9   home_club_position      40878 non-null  float64
 10  away_club_position      40878 non-null  float64
 11  home_club_manager_name  53665 non-null  object
 12  away_club_manager_name  53665 non-null  object
 13  stadium                 53845 non-null  object
 14  attendance              46392 non-null  float64
 15  referee                 53734 non-null  object
 16  url                     53888 non-null  object
 17  home_club_formation     53783 non-null  object
 18  away_club_formation     53862 non-null  object
 19  home_club_name          47885 non-null  object
 20  away_club_name          48851 non-null  object
 21  aggregate               53888 non-null  object
 22  competition_type        53888 non-null  object
dtypes: float64(3), int64(6), object(14)
memory usage: 9.9+ MB

In [11]:
#Filtering for active players in game_events using active_game_lineups

active_games_id = active_game_lineups["game_id"]
active_game_events = game_events[game_events["game_id"].isin(active_games_id)]
active_game_events.info()

<class 'pandas.core.frame.DataFrame'>
Index: 551037 entries, 71141 to 736259
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_event_id     551037 non-null  object
 1   date              551037 non-null  object
 2   game_id           551037 non-null  int64
 3   minute            551037 non-null  int64
 4   type              551037 non-null  object
 5   club_id           551037 non-null  int64
 6   player_id         551037 non-null  int64
 7   description       255692 non-null  object
 8   player_in_id      351913 non-null  float64
 9   player_assist_id  24986 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 46.2+ MB

In [12]:
#Filtering for active players in club_games using active_game_lineups

active_games_id = active_game_lineups["game_id"]
active_club_games = club_games[club_games["game_id"].isin(active_games_id)]
active_club_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 107776 entries, 0 to 136278
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   game_id                107776 non-null  int64
 1   club_id                107776 non-null  int64
 2   own_goals              107776 non-null  int64
 3   own_position           81756 non-null   float64
 4   own_manager_name       107330 non-null  object
 5   opponent_id            107776 non-null  int64
 6   opponent_goals         107776 non-null  int64
 7   opponent_position      81756 non-null   float64
 8   opponent_manager_name  107330 non-null  object
 9   hosting                107776 non-null  object
 10  is_win                 107776 non-null  int64
dtypes: float64(2), int64(6), object(3)
memory usage: 9.9+ MB

In [13]:
#Filtering for active players in appearances using active_game_lineups

active_games_id = active_game_lineups["game_id"]
active_appearances = appearances[appearances["game_id"].isin(active_games_id)]
active_appearances.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337834 entries, 130740 to 1556684
Data columns (total 13 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   appearance_id           1337834 non-null  object
 1   game_id                 1337834 non-null  int64
 2   player_id               1337834 non-null  int64
 3   player_club_id          1337834 non-null  int64
 4   player_current_club_id  1337834 non-null  int64
 5   date                    1337834 non-null  object
 6   player_name             1337833 non-null  object
 7   competition_id          1337834 non-null  object
 8   yellow_cards            1337834 non-null  int64
 9   red_cards               1337834 non-null  int64
 10  goals                   1337834 non-null  int64
 11  assists                 1337834 non-null  int64
 12  minutes_played          1337834 non-null  int64
dtypes: int64(9), object(4)
memory usage: 142.9+ MB

In [14]:
active_appearances.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
130740,2321970_133835,2321970,133835,1002,499,2013-07-04,Marko Meerits,ELQ,0,0,0,0,90
130741,2321975_104351,2321975,104351,156,4482,2013-07-04,Ramon Lopes,ELQ,0,0,0,0,9
130742,2321975_170895,2321975,170895,156,868,2013-07-04,Garry Rodrigues,ELQ,0,0,0,0,90
130743,2321975_33233,2321975,33233,156,2293,2013-07-04,Cristóvão Ramos,ELQ,0,0,0,0,81
130744,2321975_48206,2321975,48206,156,1085,2013-07-04,Nuno Pinto,ELQ,0,0,0,0,90

In [15]:
#Dropping the columns that we don't need for this project

active_players= active_players.drop(columns=['image_url', 'url'])

In [16]:
active_players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
188,3333,James,Milner,James Milner,2023,1237,james-milner,England,Leeds,England,...,Central Midfield,Midfield,right,175.0,2024-06-30 00:00:00,NaN,GB1,Brighton and Hove Albion Football Club,1000000.0,21000000.0
348,4391,Boy,Waterman,Boy Waterman,2023,383,boy-waterman,Netherlands,Lelystad,Netherlands,...,Goalkeeper,Goalkeeper,right,188.0,2024-06-30 00:00:00,Sp international,NL1,Eindhovense Voetbalvereniging Philips Sport Ve...,75000.0,3000000.0
417,5336,Anastasios,Tsokanis,Anastasios Tsokanis,2023,60949,anastasios-tsokanis,Greece,Chalkida,Greece,...,Defensive Midfield,Midfield,left,176.0,2025-06-30 00:00:00,NaN,GR1,Neos Podosferikos Syllogos Volou,450000.0,450000.0
644,7161,Jonas,Hofmann,Jonas Hofmann,2023,15,jonas-hofmann,Germany,Heidelberg,Germany,...,Attacking Midfield,Midfield,right,176.0,2027-06-30 00:00:00,Dr. Marco Gutfleisch,L1,Bayer 04 Leverkusen Fußball,13000000.0,16000000.0
723,7825,Pepe,Reina,Pepe Reina,2023,1050,pepe-reina,Spain,Madrid,Spain,...,Goalkeeper,Goalkeeper,right,188.0,2024-06-30 00:00:00,NaN,ES1,Villarreal Club de Fútbol S.A.D.,700000.0,22000000.0

In [17]:
active_players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6513 entries, 188 to 30519
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             6513 non-null   int64
 1   first_name                            6117 non-null   object
 2   last_name                             6513 non-null   object
 3   name                                  6513 non-null   object
 4   last_season                           6513 non-null   int64
 5   current_club_id                       6513 non-null   int64
 6   player_code                           6513 non-null   object
 7   country_of_birth                      6176 non-null   object
 8   city_of_birth                         6178 non-null   object
 9   country_of_citizenship                6513 non-null   object
 10  date_of_birth                         6513 non-null   object
 11  sub_position                          6509 non-null   object
 12  position                              6513 non-null   object
 13  foot                                  6322 non-null   object
 14  height_in_cm                          6341 non-null   float64
 15  contract_expiration_date              6319 non-null   object
 16  agent_name                            4602 non-null   object
 17  current_club_domestic_competition_id  6513 non-null   object
 18  current_club_name                     6513 non-null   object
 19  market_value_in_eur                   6478 non-null   float64
 20  highest_market_value_in_eur           6478 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.1+ MB

In [18]:
#Checking the players without 'market_value_in_eur'

active_players[active_players['market_value_in_eur'].isna()]

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
23208,485641,Jim,Melrose,Jim Melrose,2023,543,jim-melrose,Scotland,Glasgow,Scotland,...,Centre-Forward,Attack,NaN,NaN,NaN,NaN,GB1,Wolverhampton Wanderers Football Club,NaN,NaN
25640,592857,Frederik,Rieper,Frederik Rieper,2023,1177,frederik-rieper,NaN,NaN,Denmark,...,Centre-Back,Defender,right,196.0,2024-06-30 00:00:00,NaN,DK1,Silkeborg Idrætsforening,NaN,NaN
25798,599978,Ricardo,Sousa,Ricardo Sousa,2023,7378,ricardo-sousa,Portugal,Arouca,Portugal,...,Defensive Midfield,Midfield,right,179.0,2024-06-30 00:00:00,MadeinFootball,PO1,Portimonense Futebol SAD,NaN,NaN
27273,670711,Diogo,Pinto,Diogo Pinto,2023,336,diogo-pinto,Portugal,Felgueiras,Portugal,...,Goalkeeper,Goalkeeper,right,194.0,2024-06-30 00:00:00,MRP.POSITIONUMBER,PO1,Sporting Clube de Portugal,NaN,NaN
27610,695226,Michael,Opoku,Michael Opoku,2023,369,michael-opoku,Denmark,Copenhagen,Denmark,...,Left Winger,Attack,right,181.0,2028-06-30 00:00:00,NaN,DK1,Lyngby Boldklubben af 1921,NaN,NaN
28311,738504,NaN,João Victor,João Victor,2023,7378,joao-victor,NaN,NaN,Brazil,...,Goalkeeper,Goalkeeper,right,191.0,2024-06-30 00:00:00,Fabio Mello Sports,PO1,Portimonense Futebol SAD,NaN,NaN
28791,802547,Lasse,Flø,Lasse Flø,2023,443,lasse-flo,NaN,NaN,Denmark,...,Right-Back,Defender,NaN,NaN,2024-06-30 00:00:00,PA Group,DK1,Vejle Boldklub,NaN,NaN
28844,806948,Frank,Feller,Frank Feller,2023,2036,frank-feller,Germany,Leonberg,Germany,...,Goalkeeper,Goalkeeper,right,183.0,2025-06-30 00:00:00,SoccerQ GmbH,L1,1. Fußballclub Heidenheim 1846,NaN,NaN
28910,811794,Vladimir,Shaykhutdinov,Vladimir Shaykhutdinov,2023,2410,vladimir-shaykhutdinov,NaN,NaN,Russia,...,Goalkeeper,Goalkeeper,right,195.0,2026-06-30 00:00:00,NaN,RU1,PFK CSKA Moskva,NaN,NaN
28952,814950,Kofi,Amoako,Kofi Amoako,2023,82,kofi-amoako,NaN,NaN,Germany,...,Defensive Midfield,Midfield,NaN,186.0,2024-06-30 00:00:00,NaN,L1,Verein für Leibesübungen Wolfsburg,NaN,NaN
29090,824353,Seedy,Jarju,Seedy Jarju,2023,2036,seedy-jarju,The Gambia,Ebo Town,The Gambia,...,Left-Back,Defender,left,180.0,2025-06-30 00:00:00,HO-SPORTS-MANAGEMENT,L1,1. Fußballclub Heidenheim 1846,NaN,NaN
29246,849390,Max,Wendt,Max Wendt,2023,105,max-wendt,NaN,NaN,Germany,...,Goalkeeper,Goalkeeper,NaN,183.0,2024-06-30 00:00:00,SPORTS AGENTS CLUB,L1,Sportverein Darmstadt 1898 e. V.,NaN,NaN
29521,884810,Kjell,Wätjen,Kjell Wätjen,2023,16,kjell-watjen,Germany,Gevelsberg,Germany,...,Central Midfield,Midfield,right,183.0,2028-06-30 00:00:00,CAA Stellar,L1,Borussia Dortmund,NaN,NaN
29714,913429,Tim,Köhler,Tim Köhler,2023,23826,tim-kohler,Germany,Leipzig,Germany,...,Centre-Back,Defender,right,191.0,2026-06-30 00:00:00,NaN,L1,RasenBallsport Leipzig,NaN,NaN
29765,922413,Marko,Mladenovic,Marko Mladenovic,2023,24,marko-mladenovic,Germany,Nürtingen,Serbia,...,Attacking Midfield,Midfield,both,174.0,2024-06-30 00:00:00,NaN,L1,Eintracht Frankfurt Fußball AG,NaN,NaN
29773,923595,Max,Moerstedt,Max Moerstedt,2023,533,max-moerstedt,Germany,Mannheim,Germany,...,Centre-Forward,Attack,right,194.0,2027-06-30 00:00:00,Sports360 GmbH,L1,TSG 1899 Hoffenheim Fußball-Spielbetriebs GmbH,NaN,NaN
29828,928900,Zanos,Savva,Zanos Savva,2023,416,zanos-savva,Cyprus,Nicosia,Cyprus,...,Right Winger,Attack,left,188.0,2026-06-30 00:00:00,Mylogram Ltd,IT1,Torino Calcio,NaN,NaN
29862,932761,Viggo,Andersen,Viggo Andersen,2023,369,viggo-andersen,NaN,NaN,Denmark,...,Goalkeeper,Goalkeeper,NaN,NaN,NaN,NaN,DK1,Lyngby Boldklubben af 1921,NaN,NaN
29909,937113,Madi,Monamay,Madi Monamay,2023,15,madi-monamay,NaN,NaN,Belgium,...,Centre-Back,Defender,right,185.0,2025-06-30 00:00:00,NaN,L1,Bayer 04 Leverkusen Fußball,NaN,NaN
29988,954135,Berat,Eskin,Berat Eskin,2023,3205,berat-eskin,Türkiye,Kayseri,Türkiye,...,Defensive Midfield,Midfield,right,NaN,2028-06-30 00:00:00,NaN,TR1,Kayserispor Kulübü,NaN,NaN
30211,1017271,Gustav,Nørregaard,Gustav Nørregaard,2023,443,gustav-norregaard,NaN,NaN,Denmark,...,Goalkeeper,Goalkeeper,NaN,NaN,2025-06-30 00:00:00,NaN,DK1,Vejle Boldklub,NaN,NaN
30242,1031045,Andrew,MacLeod,Andrew MacLeod,2023,2759,andrew-macleod,Scotland,Stornoway,Scotland,...,Central Midfield,Midfield,NaN,NaN,2024-05-31 00:00:00,NaN,SC1,Ross County Football Club,NaN,NaN
30263,1037631,Freddie,Martin,Freddie Martin,2023,465,freddie-martin,NaN,NaN,England,...,Goalkeeper,Goalkeeper,right,193.0,2024-05-31 00:00:00,NaN,SC1,Saint Mirren Football Club,NaN,NaN
30269,1039787,Enock,Otoo,Enock Otoo,2023,369,enock-otoo,NaN,NaN,Ghana,...,Attacking Midfield,Midfield,NaN,NaN,2027-06-30 00:00:00,Concilium Sport,DK1,Lyngby Boldklubben af 1921,NaN,NaN
30293,1047507,Emir Mustafa,Vuruşaner,Emir Mustafa Vuruşaner,2023,924,emir-mustafa-vurusaner,Türkiye,Istanbul,Türkiye,...,Left-Back,Defender,left,NaN,NaN,NaN,TR1,İstanbulspor A.Ş.,NaN,NaN
30324,1055234,Mika,van der Horst,Mika van der Horst,2023,724,mika-van-der-horst,NaN,NaN,Netherlands,...,Central Midfield,Midfield,NaN,NaN,2027-06-30 00:00:00,Iconics Management,NL1,Football Club Volendam,NaN,NaN
30349,1066830,Andreas,Adamakis,Andreas Adamakis,2023,653,andreas-adamakis,NaN,NaN,Greece,...,NaN,Missing,NaN,NaN,2026-06-30 00:00:00,NaN,GR1,Omilos Filathlon Irakliou FC,NaN,NaN
30383,1074124,NaN,Davis,Davis,2023,7378,davis,NaN,NaN,Brazil,...,Attacking Midfield,Midfield,right,175.0,2024-06-30 00:00:00,NaN,PO1,Portimonense Futebol SAD,NaN,NaN
30448,1130086,Anders,Sønderskov,Anders Sønderskov,2023,443,anders-sonderskov,Denmark,Aarhus,Denmark,...,Centre-Back,Defender,NaN,NaN,2025-06-30 00:00:00,People In Sport,DK1,Vejle Boldklub,NaN,NaN
30488,1157759,Luca,Chavet,Luca Chavet,2023,1245,luca-chavet,NaN,NaN,Belgium,...,Centre-Back,Defender,right,190.0,2024-06-30 00:00:00,Quadrans,BE1,Königliche Allgemeine Sportvereinigung Eupen,NaN,NaN
30492,1159758,Siemen,Buvé,Siemen Buvé,2023,475,siemen-buve,NaN,NaN,Belgium,...,Goalkeeper,Goalkeeper,NaN,NaN,NaN,NaN,BE1,Koninklijke Sint-Truidense Voetbalvereniging,NaN,NaN
30504,1175926,Baran Alp,Vardar,Baran Alp Vardar,2023,924,baran-alp-vardar,Türkiye,Istanbul,Türkiye,...,Centre-Back,Defender,right,191.0,NaN,NaN,TR1,İstanbulspor A.Ş.,NaN,NaN
30517,1229924,Adama,Sidibeh,Adama Sidibeh,2023,2578,adama-sidibeh,NaN,NaN,The Gambia,...,Centre-Forward,Attack,NaN,NaN,2026-05-31 00:00:00,Willie McKay,SC1,Saint Johnstone Football Club,NaN,NaN
30518,1240467,Artem,Prysyazhnyuk,Artem Prysyazhnyuk,2023,6992,artem-prysyazhnyuk,Ukraine,Odesa,Ukraine,...,Central Midfield,Midfield,left,180.0,2025-05-31 00:00:00,NaN,UKR1,ZAO FK Chornomorets Odessa,NaN,NaN
30519,1240762,Araphat,Mohammed,Araphat Mohammed,2023,2778,araphat-mohammed,NaN,NaN,Ghana,...,Central Midfield,Midfield,left,NaN,NaN,NaN,DK1,Fodbold Club Nordsjælland,NaN,NaN

In [19]:
#Droping the players without market value

active_players = active_players.dropna(subset=['market_value_in_eur'])

In [20]:
active_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53888 entries, 0 to 68148
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 53888 non-null  int64
 1   competition_id          53888 non-null  object
 2   season                  53888 non-null  int64
 3   round                   53888 non-null  object
 4   date                    53888 non-null  object
 5   home_club_id            53888 non-null  int64
 6   away_club_id            53888 non-null  int64
 7   home_club_goals         53888 non-null  int64
 8   away_club_goals         53888 non-null  int64
 9   home_club_position      40878 non-null  float64
 10  away_club_position      40878 non-null  float64
 11  home_club_manager_name  53665 non-null  object
 12  away_club_manager_name  53665 non-null  object
 13  stadium                 53845 non-null  object
 14  attendance              46392 non-null  float64
 15  referee                 53734 non-null  object
 16  url                     53888 non-null  object
 17  home_club_formation     53783 non-null  object
 18  away_club_formation     53862 non-null  object
 19  home_club_name          47885 non-null  object
 20  away_club_name          48851 non-null  object
 21  aggregate               53888 non-null  object
 22  competition_type        53888 non-null  object
dtypes: float64(3), int64(6), object(14)
memory usage: 9.9+ MB

In [21]:
#Droping the url column from active_games

active_games= active_games.drop(columns=['url'])

In [22]:
competitions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   competition_id            43 non-null     object
 1   competition_code          43 non-null     object
 2   name                      43 non-null     object
 3   sub_type                  43 non-null     object
 4   type                      43 non-null     object
 5   country_id                43 non-null     int64
 6   country_name              36 non-null     object
 7   domestic_league_code      36 non-null     object
 8   confederation             43 non-null     object
 9   url                       43 non-null     object
 10  is_major_national_league  43 non-null     bool
dtypes: bool(1), int64(1), object(9)
memory usage: 3.5+ KB

In [23]:
#Droping the url column from competitions

competitions= competitions.drop(columns=['url'])

In [24]:
active_competitions = competitions

In [25]:
#Checking if there's players without country of birth

active_players[active_players['country_of_birth'].isna()]

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
3825,44726,Anders,Jacobsen,Anders Jacobsen,2023,443,anders-jacobsen,NaN,NaN,Denmark,...,Centre-Forward,Attack,right,181.0,2024-06-30 00:00:00,NaN,DK1,Vejle Boldklub,350000.0,1000000.0
7701,97503,Jeppe,Grønning,Jeppe Grønning,2023,1063,jeppe-gronning,NaN,NaN,Denmark,...,Defensive Midfield,Midfield,right,180.0,2026-06-30 00:00:00,NaN,DK1,Viborg Fodsports Forening,400000.0,400000.0
8023,104918,Christian,Sörensen,Christian Sörensen,2023,190,christian-sorensen,NaN,NaN,Denmark,...,Left-Back,Defender,left,179.0,2025-12-31 00:00:00,Elite Consulting,DK1,Football Club København,500000.0,500000.0
8115,107266,Marcel,Rømer,Marcel Rømer,2023,369,marcel-romer,NaN,NaN,Denmark,...,Central Midfield,Midfield,right,181.0,2025-06-30 00:00:00,People In Sport,DK1,Lyngby Boldklubben af 1921,250000.0,600000.0
10488,160117,Tobias,Thomsen,Tobias Thomsen,2023,1894,tobias-thomsen,NaN,NaN,Denmark,...,Centre-Forward,Attack,right,183.0,2024-06-30 00:00:00,Nordic Sky,DK1,Hvidovre Idrætsforening,350000.0,350000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30501,1166093,Georgios,Konstantakopoulos,Georgios Konstantakopoulos,2023,30120,georgios-konstantakopoulos,NaN,NaN,Greece,...,Defensive Midfield,Midfield,both,182.0,2026-06-30 00:00:00,SPORTS CONNECTION,GR1,Athlitiki Enosi Kifisias,250000.0,250000.0
30503,1173042,Djiby,Seck,Djiby Seck,2023,601,djiby-seck,NaN,NaN,Senegal,...,Left Winger,Attack,NaN,NaN,2025-06-30 00:00:00,NaN,BE1,Koninklijke Voetbalclub Kortrijk,150000.0,150000.0
30507,1176433,Abdoul Kader,Ouattara,Abdoul Kader Ouattara,2023,520,abdoul-kader-ouattara,NaN,NaN,Burkina Faso,...,Centre-Forward,Attack,NaN,NaN,2026-06-30 00:00:00,Forza Sports Group,BE1,Cercle Brugge Koninklijke Sportvereniging,100000.0,100000.0
30510,1186012,Bakary,Haidara,Bakary Haidara,2023,968,bakary-haidara,NaN,NaN,Cote d'Ivoire,...,Centre-Back,Defender,right,NaN,2026-06-30 00:00:00,NaN,BE1,Koninklijke Voetbal Club Westerlo,350000.0,350000.0
30512,1193194,Theodoros Georgios,Agorastos,Theodoros Georgios Agorastos,2023,605,theodoros-georgios-agorastos,NaN,NaN,Greece,...,Centre-Forward,Attack,NaN,NaN,2028-06-30 00:00:00,NaN,GR1,Aris Thessalonikis,50000.0,50000.0

In [26]:
clubs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   club_code                426 non-null    object
 2   name                     426 non-null    object
 3   domestic_competition_id  426 non-null    object
 4   total_market_value       0 non-null      float64
 5   squad_size               426 non-null    int64
 6   average_age              388 non-null    float64
 7   foreigners_number        426 non-null    int64
 8   foreigners_percentage    378 non-null    float64
 9   national_team_players    426 non-null    int64
 10  stadium_name             426 non-null    object
 11  stadium_seats            426 non-null    int64
 12  net_transfer_record      426 non-null    object
 13  coach_name               0 non-null      float64
 14  last_season              426 non-null    int64
 15  filename                 426 non-null    object
 16  url                      426 non-null    object
dtypes: float64(4), int64(6), object(7)
memory usage: 56.7+ KB

In [27]:
#Droping the columns useless for this project

clubs= clubs.drop(columns=['filename','url', 'total_market_value'])

In [28]:
clubs.head()

,club_id,club_code,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,31,26.7,11,35.5,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,27,28.1,15,55.6,6,Yekaterinburg Arena,23000,€-895k,NaN,2023
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,37,26.3,17,45.9,13,Tüpraş Stadyumu,42445,€-26.00m,NaN,2023
3,12,as-rom,Associazione Sportiva Roma,IT1,26,27.1,18,69.2,16,Olimpico di Roma,73261,+€63.20m,NaN,2023
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.7,20,76.9,20,Tottenham Hotspur Stadium,62850,€-151.40m,NaN,2023

In [29]:
clubs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   club_code                426 non-null    object
 2   name                     426 non-null    object
 3   domestic_competition_id  426 non-null    object
 4   squad_size               426 non-null    int64
 5   average_age              388 non-null    float64
 6   foreigners_number        426 non-null    int64
 7   foreigners_percentage    378 non-null    float64
 8   national_team_players    426 non-null    int64
 9   stadium_name             426 non-null    object
 10  stadium_seats            426 non-null    int64
 11  net_transfer_record      426 non-null    object
 12  coach_name               0 non-null      float64
 13  last_season              426 non-null    int64
dtypes: float64(3), int64(6), object(5)
memory usage: 46.7+ KB

In [30]:
#Taking only the clubs from last season

condition_active_clubs = (clubs['last_season'] == 2023)
active_clubs = clubs[condition_active_clubs]
active_clubs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 238 entries, 0 to 424
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  238 non-null    int64
 1   club_code                238 non-null    object
 2   name                     238 non-null    object
 3   domestic_competition_id  238 non-null    object
 4   squad_size               238 non-null    int64
 5   average_age              238 non-null    float64
 6   foreigners_number        238 non-null    int64
 7   foreigners_percentage    236 non-null    float64
 8   national_team_players    238 non-null    int64
 9   stadium_name             238 non-null    object
 10  stadium_seats            238 non-null    int64
 11  net_transfer_record      238 non-null    object
 12  coach_name               0 non-null      float64
 13  last_season              238 non-null    int64
dtypes: float64(3), int64(6), object(5)
memory usage: 27.9+ KB

In [31]:
active_clubs['club_id'].nunique()

238

In [32]:
#Converting to csv

#active_appearances.to_csv("active_appearances.csv", index= False)
#active_club_games.to_csv("active_club_games.csv", index= False)
#active_game_events.to_csv("active_game_events.csv", index= False)
#active_game_lineups.to_csv("active_game_lineups.csv", index= False)
#active_games.to_csv('active_games.csv', index= False)
#active_player_valuations.to_csv("active_player_valuations.csv", index= False)
#active_players.to_csv("active_players.csv", index= False)
#active_competitions.to_csv("active_competitions.csv", index= False)
#active_clubs.to_csv("active_clubs.csv", index= False)

In [40]:
active_players[active_players['name'] == 'Ciro Immobile']

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
8052,105521,Ciro,Immobile,Ciro Immobile,2023,398,ciro-immobile,Italy,Torre Annunziata,Italy,...,Centre-Forward,Attack,right,185.0,2026-06-30 00:00:00,Gea World,IT1,Società Sportiva Lazio S.p.A.,7000000.0,50000000.0

In [42]:
active_players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6478 entries, 188 to 30516
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             6478 non-null   int64
 1   first_name                            6084 non-null   object
 2   last_name                             6478 non-null   object
 3   name                                  6478 non-null   object
 4   last_season                           6478 non-null   int64
 5   current_club_id                       6478 non-null   int64
 6   player_code                           6478 non-null   object
 7   country_of_birth                      6159 non-null   object
 8   city_of_birth                         6161 non-null   object
 9   country_of_citizenship                6478 non-null   object
 10  date_of_birth                         6478 non-null   object
 11  sub_position                          6475 non-null   object
 12  position                              6478 non-null   object
 13  foot                                  6300 non-null   object
 14  height_in_cm                          6320 non-null   float64
 15  contract_expiration_date              6290 non-null   object
 16  agent_name                            4587 non-null   object
 17  current_club_domestic_competition_id  6478 non-null   object
 18  current_club_name                     6478 non-null   object
 19  market_value_in_eur                   6478 non-null   float64
 20  highest_market_value_in_eur           6478 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.1+ MB